language: node_js
node_js:
- 6.9.1
sudo: false
branches:
  only:
  - master
  - /^greenkeeper-.*$/
  - /^greenkeeper/.*$/
cache:
  directories:
  - node_modules
notifications:
  email:
  - torstenlink@gmx.de
  - markus.felten@gmx.de
  slack:
    secure: EiWHvzz+KRy+fJ/R0WrLW+317fCRF17zoRxpxcOZwurvrQ+Tq3FQqfTFwAlf2qZY4m9xRzfLO7aaz+cqzzfciofj2EccoiAbq44dLeyO3jji/oktosUlz0kZMCg6lpJ/oFbt+QutDdq8xzZvRy1CiEcd6KS3pnIbF7iTej5OvgEcETmlseoEVRLGvqqKZ34hLx8b3AS3ELUcMxITj/b3+455289rdicbUmSC4PmVbJDgABCHYxPN7RKszI8WF2/tsjwQaH3KSDR3YrFSPch3m061lcFX2CTZpIvVQsr7pdz3ZoccaHkaEeF59HUjPTHYMNl9kpWZPmFVa9q2lkYWQ8HLB8EoAiWo7ITccyPxpzRuQx5RKorP6Ci4ONqEQHYJ4TFPsWsuopBM28RUDFq2mRharIvENaG4q9O+N/pyISl/4SQUkGNFxoU5lpP7m7CNyCxUhO6VP30OegIkYqGD+Fmt/6lEciFwQpgXWHpmQhWjEFePdhaSxuH10jrMrsSaT98HRt1VX4aZqYvyoAwLX28RRgzaBhUBit//UkPL255/v6gTuZ94X4dWAgTyYZjRKNJRbw7K0rWX0aR/I4C/Pj7WvERaDKZnP9DyjDpXl25Kphob70L+oln44Kle/UTO1uUJGvOj6pnW5mYLOHlH1ZM7u9VRL3hH+JKkP9/+IaM=
before_install:
- npm i -g npm@latest
before_script:
- npm prune
- npm install -g codecov
script:
- npm run-script cover
after_script:
- codecov
after_success:
- npm run semantic-release
